# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm install && node node_modules/typescript/lib/tsc.js"]

[start]
cmd = "npm start"

